import { business } from './business';

export const founderMilestones = [
  {
    id: 'learning',
    title: 'Learning the trade',
    year: '2019',
    note: 'Training notes, test boards, and a notebook full of first mistakes.',
    description: 'Started with repair training and hands-on practice on broken devices.',
    quote: 'First came the patience, then the repairs.',
    statValue: '01',
    statLabel: 'Beginning',
    footerValue: '2019',
    footerLabel: 'Started learning',
  },
  {
    id: 'practice',
    title: 'Practice became routine',
    year: '2020',
    note: 'Long afternoons at the bench, repeating the same repair until it felt natural.',
    description: 'Built speed and steadiness by working on real customer repairs after training.',
    quote: 'Repetition made the hand steady.',
    statValue: 'Bench',
    statLabel: 'Practice',
    footerValue: '2020',
    footerLabel: 'Skill building',
  },
  {
    id: 'opening',
    title: 'Opening in Dighi',
    year: '2021',
    note: 'A small bench, a clear sign, and the first walk-in customers from the neighborhood.',
    description: 'RS Mobile Corner opened with honest diagnosis and personally handled repairs.',
    quote: 'The shop opened with one promise: repair it properly.',
    statValue: '2021',
    statLabel: 'Shop opened',
    footerValue: '2021',
    footerLabel: 'First day',
  },
  {
    id: 'community',
    title: 'Local referrals grew',
    year: '2022',
    note: 'Messages, referrals, and customers sending in family members and friends.',
    description: 'People began recommending the shop because the work was clear, careful, and dependable.',
    quote: 'A working phone brought the next customer in.',
    statValue: 'Word',
    statLabel: 'Of mouth',
    footerValue: '2022',
    footerLabel: 'Growing reach',
  },
  {
    id: 'advanced',
    title: 'Advanced repairs arrived',
    year: '2023',
    note: 'Board faults, micro-soldering, and repairs that need a steady hand.',
    description: 'More complex diagnostics stayed on the bench instead of being passed away.',
    quote: 'Harder faults became part of the daily work.',
    statValue: 'Board',
    statLabel: 'Level',
    footerValue: '2023',
    footerLabel: 'Advanced repair',
  },
  {
    id: 'today',
    title: 'Today, still personally repaired',
    year: 'Today',
    note: 'The same founder still handles the diagnosis and the repair.',
    description: 'Rahim Bhai continues to repair phones personally, one case at a time.',
    quote: 'The bench still belongs to the same hands.',
    statValue: 'Now',
    statLabel: 'Personally repaired',
    footerValue: 'Today',
    footerLabel: 'Current day',
  },
] as const;
